nameOverride: prometheus-app-namespace
fullnameOverride: prometheus-app-namespace

server:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  persistentVolume:
    enabled: true
    size: 8Gi

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: true

pushgateway:
  enabled: false

serviceAccounts:
  server:
    create: true
    name: prometheus-server
    annotations: {}

server:
  serviceMonitorSelectorNilUsesHelmValues: false
  serviceMonitorSelector: {}

rbac:
  create: true

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - app-namespace  # Replace with your actual namespace
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: app-namespace  # Replace with your actual namespace
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name

      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
        - role: service
          namespaces:
            names:
              - app-namespace  # Replace with your actual namespace
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: app-namespace  # Replace with your actual namespace
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_service_name

      - job_name: 'kubernetes-cadvisor'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
        metric_relabel_configs:
        - source_labels: [namespace]
          regex: app-namespace  # Replace with your actual namespace
          action: keep
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
